hpp-util: hpp::debug::Output Class Reference
hpp::debug::Output Class Reference
Debugging output.
#include </home/thomas/profiles/laas/src/unstable/hpp/hpp-util/include/hpp/util/debug.hh>
Public Member Functions
Output ()
~Output ()
virtual void write (const Channel &channel, char const *file, int line, char const *function, const std::string &data)=0
Protected Member Functions
std::ostream & writePrefix (std::ostream &stream, const Channel &channel, char const *file, int line, char const *function)
Detailed Description
Debugging output.
Represents a debugging output, i.e. an output stream which can subscribe to channels.
There is two default output:
console which points to std::cerr
journal which points to the ``journal'' file in the debugging prefix
Constructor & Destructor Documentation
hpp::debug::Output::Output () [explicit]
hpp::debug::Output::~Output ()
Member Function Documentation
virtual void hpp::debug::Output::write (const Channel & channel, char const * file, int line, char const * function, const std::string & data) [pure virtual]
Implemented in hpp::debug::JournalOutput, and hpp::debug::ConsoleOutput.
Referenced by hpp::debug::Channel::write().
std::ostream & hpp::debug::Output::writePrefix (std::ostream & stream, const Channel & channel, char const * file, int line, char const * function) [protected]
References hpp::debug::Channel::label().
Referenced by hpp::debug::JournalOutput::write(), and hpp::debug::ConsoleOutput::write().
hpp-walkfootplanner library documentation