hpp-util: hpp::debug::ConsoleOutput Class Reference
hpp::debug::ConsoleOutput Class Reference
Logging in console (std::cerr).
#include </home/thomas/profiles/laas/src/unstable/hpp/hpp-util/include/hpp/util/debug.hh>
Public Member Functions
ConsoleOutput ()
~ConsoleOutput ()
void write (const Channel &channel, char const *file, int line, char const *function, const std::string &data)
Detailed Description
Logging in console (std::cerr).
Constructor & Destructor Documentation
hpp::debug::ConsoleOutput::ConsoleOutput () [explicit]
hpp::debug::ConsoleOutput::~ConsoleOutput ()
Member Function Documentation
void hpp::debug::ConsoleOutput::write (const Channel & channel, char const * file, int line, char const * function, const std::string & data) [virtual]
Implements hpp::debug::Output.
References hpp::decindent(), hpp::incindent(), and hpp::debug::Output::writePrefix().
hpp-walkfootplanner library documentation