hpp-util: hpp::debug::Timer Class Reference
hpp::debug::Timer Class Reference
#include </home/thomas/profiles/laas/src/unstable/hpp/hpp-util/include/hpp/util/timer.hh>
Public Types
typedef boost::posix_time::ptime ptime
typedef
boost::posix_time::time_duration time_duration
typedef
boost::posix_time::time_period time_period
Public Member Functions
Timer (bool autoStart=false)
Timer (const Timer &)
Timer & operator= (const Timer &)
~Timer ()
const ptime & start ()
const ptime & stop ()
time_duration duration () const
const ptime & getStart () const
const ptime & getStop () const
std::ostream & print (std::ostream &) const
Member Typedef Documentation
typedef boost::posix_time::ptime hpp::debug::Timer::ptime
typedef boost::posix_time::time_duration hpp::debug::Timer::time_duration
typedef boost::posix_time::time_period hpp::debug::Timer::time_period
Constructor & Destructor Documentation
hpp::debug::Timer::Timer (bool autoStart = false) [explicit]
References start().
hpp::debug::Timer::Timer (const Timer & timer)
hpp::debug::Timer::~Timer ()
Member Function Documentation
Timer::time_duration hpp::debug::Timer::duration () const
Referenced by print().
const Timer::ptime & hpp::debug::Timer::getStart () const
const Timer::ptime & hpp::debug::Timer::getStop () const
Timer & hpp::debug::Timer::operator= (const Timer & timer)
std::ostream & hpp::debug::Timer::print (std::ostream & o) const
References duration().
const Timer::ptime & hpp::debug::Timer::start ()
Referenced by Timer().
const Timer::ptime & hpp::debug::Timer::stop ()
hpp-walkfootplanner library documentation