hpp-util: hpp::debug::JournalOutput Class Reference
hpp::debug::JournalOutput Class Reference
Logging in journal file in the logging directory.
#include </home/thomas/profiles/laas/src/unstable/hpp/hpp-util/include/hpp/util/debug.hh>
Public Member Functions
JournalOutput (std::string filename)
~JournalOutput ()
void write (const Channel &channel, char const *file, int line, char const *function, const std::string &data)
std::string getFilename () const
Detailed Description
Logging in journal file in the logging directory.
Constructor & Destructor Documentation
hpp::debug::JournalOutput::JournalOutput (std::string filename) [explicit]
hpp::debug::JournalOutput::~JournalOutput ()
Member Function Documentation
std::string hpp::debug::JournalOutput::getFilename () const
References getpid().
void hpp::debug::JournalOutput::write (const Channel & channel, char const * file, int line, char const * function, const std::string & data) [virtual]
Implements hpp::debug::Output.
References hpp::decindent(), hpp::iendl(), hpp::incindent(), and hpp::debug::Output::writePrefix().
hpp-walkfootplanner library documentation