hpp-util: hpp Namespace Reference
hpp Namespace Reference
Namespaces
namespace debug
namespace util
Classes
class Exception
Main exception class for HPP.
Functions
HPP_MAKE_EXCEPTION (HPP_UTIL_DLLAPI, AssertionError)
HPP_UTIL_DLLAPI std::ostream & operator<< (std::ostream &o, const Exception &exception)
Override operator<< to handle exception display.
HPP_UTIL_DLLAPI long int & indent (std::ostream &o)
The current indentation level for o.
HPP_UTIL_DLLAPI std::ostream & incindent (std::ostream &o)
Increment the indentation.
HPP_UTIL_DLLAPI std::ostream & decindent (std::ostream &o)
Decrement the indentation.
HPP_UTIL_DLLAPI std::ostream & resetindent (std::ostream &o)
Reset the indentation.
HPP_UTIL_DLLAPI std::ostream & iendl (std::ostream &o)
Print an end of line, then set the indentation.
HPP_UTIL_DLLAPI std::ostream & incendl (std::ostream &o)
Increment the indentation, print an end of line, and set the indentation.
HPP_UTIL_DLLAPI std::ostream & decendl (std::ostream &o)
Decrement the indentation, print an end of line, and set the indentation.
Function Documentation
std::ostream & hpp::decendl (std::ostream & o)
Decrement the indentation, print an end of line, and set the indentation.
References decindent(), and iendl().
std::ostream & hpp::decindent (std::ostream & o)
Decrement the indentation.
References indent().
Referenced by decendl(), hpp::debug::JournalOutput::write(), and hpp::debug::ConsoleOutput::write().
hpp::HPP_MAKE_EXCEPTION (HPP_UTIL_DLLAPI , AssertionError)
std::ostream & hpp::iendl (std::ostream & o)
Print an end of line, then set the indentation.
References indent().
Referenced by decendl(), incendl(), and hpp::debug::JournalOutput::write().
std::ostream & hpp::incendl (std::ostream & o)
Increment the indentation, print an end of line, and set the indentation.
References iendl(), and incindent().
std::ostream & hpp::incindent (std::ostream & o)
Increment the indentation.
References indent().
Referenced by incendl(), hpp::debug::JournalOutput::write(), and hpp::debug::ConsoleOutput::write().
long int & hpp::indent (std::ostream & o) [inline]
The current indentation level for o.
Referenced by decindent(), iendl(), incindent(), and resetindent().
std::ostream & hpp::operator<< (std::ostream & o, const Exception & exception)
Override operator<< to handle exception display.
Parameters:
o output stream used for display
exception exception to be displayed
Returns:
output stream
References hpp::Exception::print().
std::ostream & hpp::resetindent (std::ostream & o)
Reset the indentation.
References indent().
hpp-walkfootplanner library documentation